# 创建tensor

In [2]:
#numpy -> tensor
import numpy as np
import torch
a = np.array([2, 2, 2]) # 创建一个数组
b = torch.from_numpy(a) #从numpy数据转换成tensor
b

tensor([2, 2, 2], dtype=torch.int32)

In [3]:
a=torch.tensor([2,2]) #使用tensor()生成tensor
b=torch.FloatTensor([2,2.]) #浮点型数据tensor
c=torch.tensor([[1,2],[3,4]]) 
c

tensor([[1, 2],
        [3, 4]])

In [4]:
torch.empty(2,3)
torch.Tensor(2,3) 
torch.IntTensor(2,3) #整数型
torch.FloatTensor(2,3).type() #浮点型

'torch.FloatTensor'

In [5]:
torch.set_default_tensor_type(torch.DoubleTensor) #设置默认数据类型，如float，double，int等

In [7]:
#创建3*3的0到1均匀分布的矩阵
a=torch.rand(3,3)
#均值为0方差为1正态分布矩阵
a=torch.randn(3,3)

torch.rand_like(a)
torch.rand(a.shape)

#创建3*3的1到10随机分布的整数矩阵
torch.randint(1,10,[3,3])

tensor([[9, 6, 5],
        [1, 6, 8],
        [8, 9, 6]])

In [8]:
#创建3*3的0到1均匀分布的矩阵
a=torch.rand(3,3)
a

tensor([[0.1757, 0.2086, 0.5915],
        [0.5274, 0.6592, 0.0241],
        [0.4919, 0.8890, 0.5931]])

In [9]:
a=torch.randn(3,3)
a

tensor([[-0.4229,  0.6569,  0.3413],
        [-0.5939, -2.3641, -1.3791],
        [-0.9201,  0.1007, -1.3902]])

In [10]:
a=torch.rand(3,3)
a

tensor([[0.3021, 0.1819, 0.8952],
        [0.3353, 0.6234, 0.9661],
        [0.8168, 0.1822, 0.7740]])

In [11]:
#生成3*3的全为1的矩阵
a = torch.full([3,3],2)
a

..\aten\src\ATen\native\TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [12]:
#生成标量1
a = torch.full([],1)
a

tensor(1.)

In [13]:
a = torch.full([2],1)
a 

tensor([1., 1.])

In [14]:
a = torch.ones(3,3, 4)
a 

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#生成对角为1矩阵，若不是对角矩阵，则多余出用0填充
a = torch.eye(3,3)
a 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
a = torch.eye(3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
#生成[0,1,2,3,4,5,6,7,8,9]
a = torch.arange(0,10)
a


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#生成增量为2的数列 
b = torch.arange(0,10,2)
b

tensor([0, 2, 4, 6, 8])

In [20]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = torch.linspace(0,10,4)
a

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [22]:
#生成0~9这10个数乱序的数组（常用作索引）
a = torch.randperm(10)
a 

tensor([2, 0, 4, 6, 5, 1, 8, 9, 7, 3])

In [23]:
a[0]

tensor(2)

In [24]:
a=torch.rand(4,3,28,64)
a

tensor([[[[7.9731e-01, 9.1026e-01, 8.1812e-01,  ..., 7.7548e-01,
           9.1193e-01, 9.1541e-01],
          [3.6795e-01, 3.9442e-01, 8.8358e-01,  ..., 9.8782e-01,
           2.3070e-01, 4.2078e-01],
          [2.6930e-01, 8.9113e-01, 1.5420e-01,  ..., 2.2913e-02,
           5.3810e-01, 8.1852e-01],
          ...,
          [2.6547e-02, 5.2327e-01, 5.6970e-01,  ..., 2.2582e-01,
           8.7688e-01, 3.8426e-01],
          [2.5095e-01, 2.1932e-01, 4.8813e-01,  ..., 3.1645e-01,
           2.6028e-01, 3.3394e-01],
          [5.1535e-01, 7.4806e-01, 8.6104e-01,  ..., 9.1896e-01,
           9.6612e-01, 8.5139e-01]],

         [[9.6568e-01, 1.8597e-01, 6.9883e-01,  ..., 6.5811e-01,
           2.6325e-01, 5.9425e-01],
          [1.8095e-01, 1.7900e-01, 8.8779e-01,  ..., 9.7805e-01,
           7.2806e-01, 7.7465e-02],
          [9.2812e-01, 7.7907e-01, 8.2100e-01,  ..., 6.7729e-01,
           7.5326e-01, 7.4522e-01],
          ...,
          [4.3173e-02, 5.5415e-01, 7.1049e-01,  ..., 9.7453

In [25]:
a=torch.full([2,2],2)
a

tensor([[2., 2.],
        [2., 2.]])

In [26]:
a.pow(2)

tensor([[4., 4.],
        [4., 4.]])

In [27]:
a.sqrt()
a

tensor([[2., 2.],
        [2., 2.]])

In [33]:
a.min()

tensor(2.)

In [34]:
a.max()

tensor(2.)

In [35]:
a.argmax()

tensor(3)

In [36]:
a.argmin()

tensor(3)

In [37]:
a.sum()

tensor(8.)

In [42]:
a.topk(2)

torch.return_types.topk(
values=tensor([[2., 2.],
        [2., 2.]]),
indices=tensor([[0, 1],
        [0, 1]]))